# Generated by Django 4.2.29 on 2026-05-08 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monthly_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('morning_summary', models.BooleanField(default=True)),
                ('evening_summary', models.BooleanField(default=True)),
                ('notification_time', models.TimeField(blank=True, null=True)),
                ('voice_enabled', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_preferences',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('direction', models.CharField(choices=[('in', 'Input'), ('out', 'Output')], max_length=10)),
                ('action_taken', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'conversations',
                'ordering': ['created_at'],
            },
        ),
    ]
