# Generated by Django 4.2.29 on 2026-05-08 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('food', 'Comida 🍔'), ('transport', 'Transporte 🚗'), ('entertainment', 'Entretenimiento 🎬'), ('shopping', 'Compras 🛒'), ('health', 'Salud 💊'), ('home', 'Hogar 🏠'), ('education', 'Educación 📚'), ('travel', 'Viajes ✈️'), ('income', 'Ingresos 💰'), ('other', 'Otros 📦')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('recurring', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('food', 'Comida 🍔'), ('transport', 'Transporte 🚗'), ('entertainment', 'Entretenimiento 🎬'), ('shopping', 'Compras 🛒'), ('health', 'Salud 💊'), ('home', 'Hogar 🏠'), ('education', 'Educación 📚'), ('travel', 'Viajes ✈️'), ('income', 'Ingresos 💰'), ('other', 'Otros 📦')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('period', models.CharField(default='monthly', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'budgets',
            },
        ),
    ]
